### ISSUE TITLE
Instructions in the ReadMe file is wrong

### ISSUE THREAD

**Issue by yemiwebby** [cometchat-pro/cometchat-pro-vue-ui-kit#1]
### Describe the problem

> This is not really a bug but a request to review the set of instructions stated on the README section of this repository.

### What was the expected behavior?

> The instructions should reference the name of the new repository and not the previous one. It's becoming pretty difficult to follow properly.

**Comment by prakash-cometchat** [comment]
Thanks for informing @yemiwebby . We have modified our document in recent times. Closing the issue.
